services:
  radarr:
    image: ghcr.io/onedr0p/radarr:5.14.0
    restart: unless-stopped
    user: "568"
    environment:
      - TZ=Europe/London
      - RADARR__PORT=80
    volumes:
      - /srv/containers/storage/ssd/radarr:/config:rw
      - /srv/containers/storage/hdd/media:/media:rw
  prowlarr:
    image: ghcr.io/onedr0p/prowlarr:1.31.2
    restart: unless-stopped
    user: "568"
    environment:
      - TZ=Europe/London
      - PROWLARR__PORT=80
    volumes:
      - /srv/containers/storage/ssd/prowlarr:/config:rw
  sonarr:
    image: ghcr.io/onedr0p/sonarr:4.0.10
    restart: unless-stopped
    user: "568"
    environment:
      - TZ=Europe/London
    volumes:
      - /srv/containers/storage/ssd/sonarr:/config:rw
      - /srv/containers/storage/hdd/media:/media:rw
