services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.19.5
    restart: unless-stopped
    user: "568"
    environment:
      - TZ=Europe/London
      - PORT=8080
      - AUDIOBOOKSHELF_UID=568
      - AUDIOBOOKSHELF_GID=568
    volumes:
      - /srv/containers/storage/hdd/media:/media:rw
      - /srv/containers/storage/ssd/audiobookshelf/config:/config:rw
      - /srv/containers/storage/ssd/audiobookshelf/metadata:/metadata:rw
      - /srv/containers/storage/ssd/audiobookshelf/cache:/cache:rw