services:
  overseerr:
    image: ghcr.io/sct/overseerr:1.33.2
    restart: unless-stopped
    user: "568"
    environment:
      - TZ=Europe/London
      - LOG_LEVEL=info
      - PORT=80
    volumes:
      - /srv/containers/storage/ssd/overseerr:/app/config:rw